// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.0
// source: common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Статусы заказа
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_CREATED    OrderStatus = 0 // Создан
	OrderStatus_ORDER_STATUS_COOKING    OrderStatus = 1 // Готовится
	OrderStatus_ORDER_STATUS_READY      OrderStatus = 2 // Готов
	OrderStatus_ORDER_STATUS_DELIVERING OrderStatus = 3 // В процессе доставки
	OrderStatus_ORDER_STATUS_DELIVERED  OrderStatus = 4 // Отдан заказчику
	OrderStatus_ORDER_STATUS_CANCELED   OrderStatus = 5 // Отменен
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_CREATED",
		1: "ORDER_STATUS_COOKING",
		2: "ORDER_STATUS_READY",
		3: "ORDER_STATUS_DELIVERING",
		4: "ORDER_STATUS_DELIVERED",
		5: "ORDER_STATUS_CANCELED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_CREATED":    0,
		"ORDER_STATUS_COOKING":    1,
		"ORDER_STATUS_READY":      2,
		"ORDER_STATUS_DELIVERING": 3,
		"ORDER_STATUS_DELIVERED":  4,
		"ORDER_STATUS_CANCELED":   5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type UserRole int32

const (
	UserRole_USER_ROLE_CUSTOMER   UserRole = 0
	UserRole_USER_ROLE_RESTAURANT UserRole = 1
	UserRole_USER_ROLE_COURIER    UserRole = 2
	UserRole_USER_ROLE_ADMIN      UserRole = 3
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_CUSTOMER",
		1: "USER_ROLE_RESTAURANT",
		2: "USER_ROLE_COURIER",
		3: "USER_ROLE_ADMIN",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_CUSTOMER":   0,
		"USER_ROLE_RESTAURANT": 1,
		"USER_ROLE_COURIER":    2,
		"USER_ROLE_ADMIN":      3,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// Позиция в заказе
type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"` // id товара
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                            // Название
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`                   // Количество
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`                         // Цена
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// Модель заказа
type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                         // id заказа
	RestaurantId  string                 `protobuf:"bytes,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"` // id ресторана
	CourierId     string                 `protobuf:"bytes,3,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`          // id курьера
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`             // id заказчика
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`                               // Адрес доставки
	Items         []*OrderItem           `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`                                   // Товары в заказе
	TotalPrice    int64                  `protobuf:"varint,7,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`      // Общая стоимость
	Status        OrderStatus            `protobuf:"varint,8,opt,name=status,proto3,enum=common.OrderStatus" json:"status,omitempty"`        // Статус заказа
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *Order) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

func (x *Order) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Order) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetTotalPrice() int64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_CREATED
}

// Адрес доставки (пока оставил на будущее)
type DeliveryAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	Building      string                 `protobuf:"bytes,2,opt,name=building,proto3" json:"building,omitempty"`
	Apartment     string                 `protobuf:"bytes,3,opt,name=apartment,proto3" json:"apartment,omitempty"`
	Entrance      string                 `protobuf:"bytes,4,opt,name=entrance,proto3" json:"entrance,omitempty"`
	Floor         string                 `protobuf:"bytes,5,opt,name=floor,proto3" json:"floor,omitempty"`
	Comment       string                 `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryAddress) Reset() {
	*x = DeliveryAddress{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryAddress) ProtoMessage() {}

func (x *DeliveryAddress) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryAddress.ProtoReflect.Descriptor instead.
func (*DeliveryAddress) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *DeliveryAddress) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *DeliveryAddress) GetBuilding() string {
	if x != nil {
		return x.Building
	}
	return ""
}

func (x *DeliveryAddress) GetApartment() string {
	if x != nil {
		return x.Apartment
	}
	return ""
}

func (x *DeliveryAddress) GetEntrance() string {
	if x != nil {
		return x.Entrance
	}
	return ""
}

func (x *DeliveryAddress) GetFloor() string {
	if x != nil {
		return x.Floor
	}
	return ""
}

func (x *DeliveryAddress) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// Базовый профиль - для любого пользователя
type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Role          UserRole               `protobuf:"varint,3,opt,name=role,proto3,enum=common.UserRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *UserProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfile) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_USER_ROLE_CUSTOMER
}

// Расширенный профиль ресторана
type RestaurantProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Rating        float64                `protobuf:"fixed64,6,opt,name=rating,proto3" json:"rating,omitempty"` // средний рейтинг
	IsOpen        bool                   `protobuf:"varint,7,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantProfile) Reset() {
	*x = RestaurantProfile{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantProfile) ProtoMessage() {}

func (x *RestaurantProfile) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantProfile.ProtoReflect.Descriptor instead.
func (*RestaurantProfile) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *RestaurantProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RestaurantProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestaurantProfile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RestaurantProfile) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RestaurantProfile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RestaurantProfile) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *RestaurantProfile) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

// Расширенный профиль курьера
type CourierProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"` // доступен для заказов
	Rating        float64                `protobuf:"fixed64,5,opt,name=rating,proto3" json:"rating,omitempty"`                    // средний рейтинг
	Earnings      int64                  `protobuf:"varint,6,opt,name=earnings,proto3" json:"earnings,omitempty"`                 // общий заработок
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourierProfile) Reset() {
	*x = CourierProfile{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourierProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierProfile) ProtoMessage() {}

func (x *CourierProfile) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierProfile.ProtoReflect.Descriptor instead.
func (*CourierProfile) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *CourierProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CourierProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CourierProfile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CourierProfile) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CourierProfile) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CourierProfile) GetEarnings() int64 {
	if x != nil {
		return x.Earnings
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x06common\"p\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\"\x89\x02\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rrestaurant_id\x18\x02 \x01(\tR\frestaurantId\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x03 \x01(\tR\tcourierId\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12'\n" +
	"\x05items\x18\x06 \x03(\v2\x11.common.OrderItemR\x05items\x12\x1f\n" +
	"\vtotal_price\x18\a \x01(\x03R\n" +
	"totalPrice\x12+\n" +
	"\x06status\x18\b \x01(\x0e2\x13.common.OrderStatusR\x06status\"\xaf\x01\n" +
	"\x0fDeliveryAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x1a\n" +
	"\bbuilding\x18\x02 \x01(\tR\bbuilding\x12\x1c\n" +
	"\tapartment\x18\x03 \x01(\tR\tapartment\x12\x1a\n" +
	"\bentrance\x18\x04 \x01(\tR\bentrance\x12\x14\n" +
	"\x05floor\x18\x05 \x01(\tR\x05floor\x12\x18\n" +
	"\acomment\x18\x06 \x01(\tR\acomment\"_\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12$\n" +
	"\x04role\x18\x03 \x01(\x0e2\x10.common.UserRoleR\x04role\"\xba\x01\n" +
	"\x11RestaurantProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x01R\x06rating\x12\x17\n" +
	"\ais_open\x18\a \x01(\bR\x06isOpen\"\x9b\x01\n" +
	"\x0eCourierProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x01R\x06rating\x12\x1a\n" +
	"\bearnings\x18\x06 \x01(\x03R\bearnings*\xad\x01\n" +
	"\vOrderStatus\x12\x18\n" +
	"\x14ORDER_STATUS_CREATED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_COOKING\x10\x01\x12\x16\n" +
	"\x12ORDER_STATUS_READY\x10\x02\x12\x1b\n" +
	"\x17ORDER_STATUS_DELIVERING\x10\x03\x12\x1a\n" +
	"\x16ORDER_STATUS_DELIVERED\x10\x04\x12\x19\n" +
	"\x15ORDER_STATUS_CANCELED\x10\x05*h\n" +
	"\bUserRole\x12\x16\n" +
	"\x12USER_ROLE_CUSTOMER\x10\x00\x12\x18\n" +
	"\x14USER_ROLE_RESTAURANT\x10\x01\x12\x15\n" +
	"\x11USER_ROLE_COURIER\x10\x02\x12\x13\n" +
	"\x0fUSER_ROLE_ADMIN\x10\x03B.Z,github.com/suhrobdomoiZ/Eda-1/pkg/api/commonb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_common_proto_goTypes = []any{
	(OrderStatus)(0),          // 0: common.OrderStatus
	(UserRole)(0),             // 1: common.UserRole
	(*OrderItem)(nil),         // 2: common.OrderItem
	(*Order)(nil),             // 3: common.Order
	(*DeliveryAddress)(nil),   // 4: common.DeliveryAddress
	(*UserProfile)(nil),       // 5: common.UserProfile
	(*RestaurantProfile)(nil), // 6: common.RestaurantProfile
	(*CourierProfile)(nil),    // 7: common.CourierProfile
}
var file_common_proto_depIdxs = []int32{
	2, // 0: common.Order.items:type_name -> common.OrderItem
	0, // 1: common.Order.status:type_name -> common.OrderStatus
	1, // 2: common.UserProfile.role:type_name -> common.UserRole
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
