stages:
  - test
  - build

variables:
  GO_VERSION: "1.26.1"
  REGISTRY: $CI_REGISTRY_IMAGE


# Test 

test:
  stage: test
  image: golang:1.26.1
  before_script:
    - go mod download
  script:
    - go test -v -race -coverprofile=coverage.out ./services/auth/...
    - go test -v -race -coverprofile=coverage_gateway.out ./services/api_gateway/...
    - go tool cover -func=coverage.out
    - go tool cover -func=coverage_gateway.out
  coverage: '/total:\s+\(statements\)\s+(\d+\.\d+)%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.out
    paths:
      - coverage.out
      - coverage_gateway.out
    expire_in: 1 week
  cache:
    key: ${CI_COMMIT_REF_SLUG}-test
    paths:
      - /root/go/pkg/mod
# Build 
.build_template:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.0-debug
    entrypoint: [""]
  script:
    - |
      /kaniko/executor \
        --context "${CI_PROJECT_DIR}" \
        --dockerfile "services/${SERVICE}/Dockerfile" \
        --destination "$REGISTRY/${SERVICE}:${CI_COMMIT_SHORT_SHA}" \
        --destination "$REGISTRY/${SERVICE}:latest" \
        --cache=true \
        --cache-ttl=24h
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

# Build  

build:auth:
  extends: .build_template
  variables:
    SERVICE: auth

build:api_gateway:
  extends: .build_template
  variables:
    SERVICE: api_gateway

build:customer:
  extends: .build_template
  variables:
    SERVICE: customer

build:restaurant:
  extends: .build_template
  variables:
    SERVICE: restaurant

build:courier:
  extends: .build_template
  variables:
    SERVICE: courier