// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: courier.proto

package courier

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientAPI_GetAvailableOrders_FullMethodName = "/courier.ClientAPI/GetAvailableOrders"
	ClientAPI_AcceptOrder_FullMethodName        = "/courier.ClientAPI/AcceptOrder"
	ClientAPI_GetMyOrders_FullMethodName        = "/courier.ClientAPI/GetMyOrders"
	ClientAPI_PickUpOrder_FullMethodName        = "/courier.ClientAPI/PickUpOrder"
	ClientAPI_DeliverOrder_FullMethodName       = "/courier.ClientAPI/DeliverOrder"
)

// ClientAPIClient is the client API for ClientAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// API заказчика
type ClientAPIClient interface {
	GetAvailableOrders(ctx context.Context, in *GetAvailableOrdersRequest, opts ...grpc.CallOption) (*GetAvailableOrdersResponse, error)
	AcceptOrder(ctx context.Context, in *AcceptOrderRequest, opts ...grpc.CallOption) (*AcceptOrderResponse, error)
	GetMyOrders(ctx context.Context, in *GetMyOrdersRequest, opts ...grpc.CallOption) (*GetMyOrdersResponse, error)
	PickUpOrder(ctx context.Context, in *PickUpOrderRequest, opts ...grpc.CallOption) (*PickUpOrderResponse, error)
	DeliverOrder(ctx context.Context, in *DeliverOrderRequest, opts ...grpc.CallOption) (*DeliverOrderResponse, error)
}

type clientAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewClientAPIClient(cc grpc.ClientConnInterface) ClientAPIClient {
	return &clientAPIClient{cc}
}

func (c *clientAPIClient) GetAvailableOrders(ctx context.Context, in *GetAvailableOrdersRequest, opts ...grpc.CallOption) (*GetAvailableOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableOrdersResponse)
	err := c.cc.Invoke(ctx, ClientAPI_GetAvailableOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientAPIClient) AcceptOrder(ctx context.Context, in *AcceptOrderRequest, opts ...grpc.CallOption) (*AcceptOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptOrderResponse)
	err := c.cc.Invoke(ctx, ClientAPI_AcceptOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientAPIClient) GetMyOrders(ctx context.Context, in *GetMyOrdersRequest, opts ...grpc.CallOption) (*GetMyOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyOrdersResponse)
	err := c.cc.Invoke(ctx, ClientAPI_GetMyOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientAPIClient) PickUpOrder(ctx context.Context, in *PickUpOrderRequest, opts ...grpc.CallOption) (*PickUpOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PickUpOrderResponse)
	err := c.cc.Invoke(ctx, ClientAPI_PickUpOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientAPIClient) DeliverOrder(ctx context.Context, in *DeliverOrderRequest, opts ...grpc.CallOption) (*DeliverOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverOrderResponse)
	err := c.cc.Invoke(ctx, ClientAPI_DeliverOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientAPIServer is the server API for ClientAPI service.
// All implementations must embed UnimplementedClientAPIServer
// for forward compatibility.
//
// API заказчика
type ClientAPIServer interface {
	GetAvailableOrders(context.Context, *GetAvailableOrdersRequest) (*GetAvailableOrdersResponse, error)
	AcceptOrder(context.Context, *AcceptOrderRequest) (*AcceptOrderResponse, error)
	GetMyOrders(context.Context, *GetMyOrdersRequest) (*GetMyOrdersResponse, error)
	PickUpOrder(context.Context, *PickUpOrderRequest) (*PickUpOrderResponse, error)
	DeliverOrder(context.Context, *DeliverOrderRequest) (*DeliverOrderResponse, error)
	mustEmbedUnimplementedClientAPIServer()
}

// UnimplementedClientAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientAPIServer struct{}

func (UnimplementedClientAPIServer) GetAvailableOrders(context.Context, *GetAvailableOrdersRequest) (*GetAvailableOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableOrders not implemented")
}
func (UnimplementedClientAPIServer) AcceptOrder(context.Context, *AcceptOrderRequest) (*AcceptOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptOrder not implemented")
}
func (UnimplementedClientAPIServer) GetMyOrders(context.Context, *GetMyOrdersRequest) (*GetMyOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyOrders not implemented")
}
func (UnimplementedClientAPIServer) PickUpOrder(context.Context, *PickUpOrderRequest) (*PickUpOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PickUpOrder not implemented")
}
func (UnimplementedClientAPIServer) DeliverOrder(context.Context, *DeliverOrderRequest) (*DeliverOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliverOrder not implemented")
}
func (UnimplementedClientAPIServer) mustEmbedUnimplementedClientAPIServer() {}
func (UnimplementedClientAPIServer) testEmbeddedByValue()                   {}

// UnsafeClientAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientAPIServer will
// result in compilation errors.
type UnsafeClientAPIServer interface {
	mustEmbedUnimplementedClientAPIServer()
}

func RegisterClientAPIServer(s grpc.ServiceRegistrar, srv ClientAPIServer) {
	// If the following call panics, it indicates UnimplementedClientAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientAPI_ServiceDesc, srv)
}

func _ClientAPI_GetAvailableOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientAPIServer).GetAvailableOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientAPI_GetAvailableOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientAPIServer).GetAvailableOrders(ctx, req.(*GetAvailableOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientAPI_AcceptOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientAPIServer).AcceptOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientAPI_AcceptOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientAPIServer).AcceptOrder(ctx, req.(*AcceptOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientAPI_GetMyOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientAPIServer).GetMyOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientAPI_GetMyOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientAPIServer).GetMyOrders(ctx, req.(*GetMyOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientAPI_PickUpOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PickUpOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientAPIServer).PickUpOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientAPI_PickUpOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientAPIServer).PickUpOrder(ctx, req.(*PickUpOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientAPI_DeliverOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientAPIServer).DeliverOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientAPI_DeliverOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientAPIServer).DeliverOrder(ctx, req.(*DeliverOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientAPI_ServiceDesc is the grpc.ServiceDesc for ClientAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "courier.ClientAPI",
	HandlerType: (*ClientAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAvailableOrders",
			Handler:    _ClientAPI_GetAvailableOrders_Handler,
		},
		{
			MethodName: "AcceptOrder",
			Handler:    _ClientAPI_AcceptOrder_Handler,
		},
		{
			MethodName: "GetMyOrders",
			Handler:    _ClientAPI_GetMyOrders_Handler,
		},
		{
			MethodName: "PickUpOrder",
			Handler:    _ClientAPI_PickUpOrder_Handler,
		},
		{
			MethodName: "DeliverOrder",
			Handler:    _ClientAPI_DeliverOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "courier.proto",
}
