// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: courier.proto

package courier

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CourierAPI_GetAvailableOrders_FullMethodName = "/courier.CourierAPI/GetAvailableOrders"
	CourierAPI_AcceptOrder_FullMethodName        = "/courier.CourierAPI/AcceptOrder"
	CourierAPI_GetMyOrders_FullMethodName        = "/courier.CourierAPI/GetMyOrders"
	CourierAPI_PickUpOrder_FullMethodName        = "/courier.CourierAPI/PickUpOrder"
	CourierAPI_DeliverOrder_FullMethodName       = "/courier.CourierAPI/DeliverOrder"
)

// CourierAPIClient is the client API for CourierAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// API курьера
type CourierAPIClient interface {
	GetAvailableOrders(ctx context.Context, in *GetAvailableOrdersRequest, opts ...grpc.CallOption) (*GetAvailableOrdersResponse, error)
	AcceptOrder(ctx context.Context, in *AcceptOrderRequest, opts ...grpc.CallOption) (*AcceptOrderResponse, error)
	GetMyOrders(ctx context.Context, in *GetMyOrdersRequest, opts ...grpc.CallOption) (*GetMyOrdersResponse, error)
	PickUpOrder(ctx context.Context, in *PickUpOrderRequest, opts ...grpc.CallOption) (*PickUpOrderResponse, error)
	DeliverOrder(ctx context.Context, in *DeliverOrderRequest, opts ...grpc.CallOption) (*DeliverOrderResponse, error)
}

type courierAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewCourierAPIClient(cc grpc.ClientConnInterface) CourierAPIClient {
	return &courierAPIClient{cc}
}

func (c *courierAPIClient) GetAvailableOrders(ctx context.Context, in *GetAvailableOrdersRequest, opts ...grpc.CallOption) (*GetAvailableOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableOrdersResponse)
	err := c.cc.Invoke(ctx, CourierAPI_GetAvailableOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courierAPIClient) AcceptOrder(ctx context.Context, in *AcceptOrderRequest, opts ...grpc.CallOption) (*AcceptOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptOrderResponse)
	err := c.cc.Invoke(ctx, CourierAPI_AcceptOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courierAPIClient) GetMyOrders(ctx context.Context, in *GetMyOrdersRequest, opts ...grpc.CallOption) (*GetMyOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyOrdersResponse)
	err := c.cc.Invoke(ctx, CourierAPI_GetMyOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courierAPIClient) PickUpOrder(ctx context.Context, in *PickUpOrderRequest, opts ...grpc.CallOption) (*PickUpOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PickUpOrderResponse)
	err := c.cc.Invoke(ctx, CourierAPI_PickUpOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courierAPIClient) DeliverOrder(ctx context.Context, in *DeliverOrderRequest, opts ...grpc.CallOption) (*DeliverOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverOrderResponse)
	err := c.cc.Invoke(ctx, CourierAPI_DeliverOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CourierAPIServer is the server API for CourierAPI service.
// All implementations must embed UnimplementedCourierAPIServer
// for forward compatibility.
//
// API курьера
type CourierAPIServer interface {
	GetAvailableOrders(context.Context, *GetAvailableOrdersRequest) (*GetAvailableOrdersResponse, error)
	AcceptOrder(context.Context, *AcceptOrderRequest) (*AcceptOrderResponse, error)
	GetMyOrders(context.Context, *GetMyOrdersRequest) (*GetMyOrdersResponse, error)
	PickUpOrder(context.Context, *PickUpOrderRequest) (*PickUpOrderResponse, error)
	DeliverOrder(context.Context, *DeliverOrderRequest) (*DeliverOrderResponse, error)
	mustEmbedUnimplementedCourierAPIServer()
}

// UnimplementedCourierAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCourierAPIServer struct{}

func (UnimplementedCourierAPIServer) GetAvailableOrders(context.Context, *GetAvailableOrdersRequest) (*GetAvailableOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableOrders not implemented")
}
func (UnimplementedCourierAPIServer) AcceptOrder(context.Context, *AcceptOrderRequest) (*AcceptOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptOrder not implemented")
}
func (UnimplementedCourierAPIServer) GetMyOrders(context.Context, *GetMyOrdersRequest) (*GetMyOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyOrders not implemented")
}
func (UnimplementedCourierAPIServer) PickUpOrder(context.Context, *PickUpOrderRequest) (*PickUpOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PickUpOrder not implemented")
}
func (UnimplementedCourierAPIServer) DeliverOrder(context.Context, *DeliverOrderRequest) (*DeliverOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliverOrder not implemented")
}
func (UnimplementedCourierAPIServer) mustEmbedUnimplementedCourierAPIServer() {}
func (UnimplementedCourierAPIServer) testEmbeddedByValue()                    {}

// UnsafeCourierAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CourierAPIServer will
// result in compilation errors.
type UnsafeCourierAPIServer interface {
	mustEmbedUnimplementedCourierAPIServer()
}

func RegisterCourierAPIServer(s grpc.ServiceRegistrar, srv CourierAPIServer) {
	// If the following call panics, it indicates UnimplementedCourierAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CourierAPI_ServiceDesc, srv)
}

func _CourierAPI_GetAvailableOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierAPIServer).GetAvailableOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourierAPI_GetAvailableOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierAPIServer).GetAvailableOrders(ctx, req.(*GetAvailableOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourierAPI_AcceptOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierAPIServer).AcceptOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourierAPI_AcceptOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierAPIServer).AcceptOrder(ctx, req.(*AcceptOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourierAPI_GetMyOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierAPIServer).GetMyOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourierAPI_GetMyOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierAPIServer).GetMyOrders(ctx, req.(*GetMyOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourierAPI_PickUpOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PickUpOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierAPIServer).PickUpOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourierAPI_PickUpOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierAPIServer).PickUpOrder(ctx, req.(*PickUpOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourierAPI_DeliverOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierAPIServer).DeliverOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourierAPI_DeliverOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierAPIServer).DeliverOrder(ctx, req.(*DeliverOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CourierAPI_ServiceDesc is the grpc.ServiceDesc for CourierAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CourierAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "courier.CourierAPI",
	HandlerType: (*CourierAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAvailableOrders",
			Handler:    _CourierAPI_GetAvailableOrders_Handler,
		},
		{
			MethodName: "AcceptOrder",
			Handler:    _CourierAPI_AcceptOrder_Handler,
		},
		{
			MethodName: "GetMyOrders",
			Handler:    _CourierAPI_GetMyOrders_Handler,
		},
		{
			MethodName: "PickUpOrder",
			Handler:    _CourierAPI_PickUpOrder_Handler,
		},
		{
			MethodName: "DeliverOrder",
			Handler:    _CourierAPI_DeliverOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "courier.proto",
}
