// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: courier.proto

package api

import (
	common "github.com/suhrobdomoiZ/Eda-1/pkg/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAvailableOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableOrdersRequest) Reset() {
	*x = GetAvailableOrdersRequest{}
	mi := &file_courier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableOrdersRequest) ProtoMessage() {}

func (x *GetAvailableOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableOrdersRequest) Descriptor() ([]byte, []int) {
	return file_courier_proto_rawDescGZIP(), []int{0}
}

func (x *GetAvailableOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetAvailableOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*common.Order        `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableOrdersResponse) Reset() {
	*x = GetAvailableOrdersResponse{}
	mi := &file_courier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableOrdersResponse) ProtoMessage() {}

func (x *GetAvailableOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableOrdersResponse) Descriptor() ([]byte, []int) {
	return file_courier_proto_rawDescGZIP(), []int{1}
}

func (x *GetAvailableOrdersResponse) GetOrders() []*common.Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type AcceptOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptOrderRequest) Reset() {
	*x = AcceptOrderRequest{}
	mi := &file_courier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptOrderRequest) ProtoMessage() {}

func (x *AcceptOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptOrderRequest.ProtoReflect.Descriptor instead.
func (*AcceptOrderRequest) Descriptor() ([]byte, []int) {
	return file_courier_proto_rawDescGZIP(), []int{2}
}

func (x *AcceptOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type AcceptOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Order         *common.Order          `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"` // Полная информация о заказе
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptOrderResponse) Reset() {
	*x = AcceptOrderResponse{}
	mi := &file_courier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptOrderResponse) ProtoMessage() {}

func (x *AcceptOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptOrderResponse.ProtoReflect.Descriptor instead.
func (*AcceptOrderResponse) Descriptor() ([]byte, []int) {
	return file_courier_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AcceptOrderResponse) GetOrder() *common.Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetMyOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourierId     string                 `protobuf:"bytes,1,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyOrdersRequest) Reset() {
	*x = GetMyOrdersRequest{}
	mi := &file_courier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyOrdersRequest) ProtoMessage() {}

func (x *GetMyOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetMyOrdersRequest) Descriptor() ([]byte, []int) {
	return file_courier_proto_rawDescGZIP(), []int{4}
}

func (x *GetMyOrdersRequest) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

type GetMyOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*common.Order        `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyOrdersResponse) Reset() {
	*x = GetMyOrdersResponse{}
	mi := &file_courier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyOrdersResponse) ProtoMessage() {}

func (x *GetMyOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetMyOrdersResponse) Descriptor() ([]byte, []int) {
	return file_courier_proto_rawDescGZIP(), []int{5}
}

func (x *GetMyOrdersResponse) GetOrders() []*common.Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type PickUpOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickUpOrderRequest) Reset() {
	*x = PickUpOrderRequest{}
	mi := &file_courier_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickUpOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickUpOrderRequest) ProtoMessage() {}

func (x *PickUpOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courier_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickUpOrderRequest.ProtoReflect.Descriptor instead.
func (*PickUpOrderRequest) Descriptor() ([]byte, []int) {
	return file_courier_proto_rawDescGZIP(), []int{6}
}

func (x *PickUpOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type PickUpOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Status        common.OrderStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=common.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickUpOrderResponse) Reset() {
	*x = PickUpOrderResponse{}
	mi := &file_courier_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickUpOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickUpOrderResponse) ProtoMessage() {}

func (x *PickUpOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courier_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickUpOrderResponse.ProtoReflect.Descriptor instead.
func (*PickUpOrderResponse) Descriptor() ([]byte, []int) {
	return file_courier_proto_rawDescGZIP(), []int{7}
}

func (x *PickUpOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PickUpOrderResponse) GetStatus() common.OrderStatus {
	if x != nil {
		return x.Status
	}
	return common.OrderStatus(0)
}

type DeliverOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverOrderRequest) Reset() {
	*x = DeliverOrderRequest{}
	mi := &file_courier_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverOrderRequest) ProtoMessage() {}

func (x *DeliverOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courier_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverOrderRequest.ProtoReflect.Descriptor instead.
func (*DeliverOrderRequest) Descriptor() ([]byte, []int) {
	return file_courier_proto_rawDescGZIP(), []int{8}
}

func (x *DeliverOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type DeliverOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Status        common.OrderStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=common.OrderStatus" json:"status,omitempty"`
	Earnings      int64                  `protobuf:"varint,3,opt,name=earnings,proto3" json:"earnings,omitempty"` // Заработок за этот заказ
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverOrderResponse) Reset() {
	*x = DeliverOrderResponse{}
	mi := &file_courier_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverOrderResponse) ProtoMessage() {}

func (x *DeliverOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courier_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverOrderResponse.ProtoReflect.Descriptor instead.
func (*DeliverOrderResponse) Descriptor() ([]byte, []int) {
	return file_courier_proto_rawDescGZIP(), []int{9}
}

func (x *DeliverOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeliverOrderResponse) GetStatus() common.OrderStatus {
	if x != nil {
		return x.Status
	}
	return common.OrderStatus(0)
}

func (x *DeliverOrderResponse) GetEarnings() int64 {
	if x != nil {
		return x.Earnings
	}
	return 0
}

var File_courier_proto protoreflect.FileDescriptor

const file_courier_proto_rawDesc = "" +
	"\n" +
	"\rcourier.proto\x12\acourier\x1a\fcommon.proto\"1\n" +
	"\x19GetAvailableOrdersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"C\n" +
	"\x1aGetAvailableOrdersResponse\x12%\n" +
	"\x06orders\x18\x01 \x03(\v2\r.common.OrderR\x06orders\"/\n" +
	"\x12AcceptOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"T\n" +
	"\x13AcceptOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\x05order\x18\x02 \x01(\v2\r.common.OrderR\x05order\"3\n" +
	"\x12GetMyOrdersRequest\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x01 \x01(\tR\tcourierId\"<\n" +
	"\x13GetMyOrdersResponse\x12%\n" +
	"\x06orders\x18\x01 \x03(\v2\r.common.OrderR\x06orders\"/\n" +
	"\x12PickUpOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\\\n" +
	"\x13PickUpOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.common.OrderStatusR\x06status\"0\n" +
	"\x13DeliverOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"y\n" +
	"\x14DeliverOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.common.OrderStatusR\x06status\x12\x1a\n" +
	"\bearnings\x18\x03 \x01(\x03R\bearnings2\x95\x03\n" +
	"\tClientAPI\x12]\n" +
	"\x12GetAvailableOrders\x12\".courier.GetAvailableOrdersRequest\x1a#.courier.GetAvailableOrdersResponse\x12H\n" +
	"\vAcceptOrder\x12\x1b.courier.AcceptOrderRequest\x1a\x1c.courier.AcceptOrderResponse\x12H\n" +
	"\vGetMyOrders\x12\x1b.courier.GetMyOrdersRequest\x1a\x1c.courier.GetMyOrdersResponse\x12H\n" +
	"\vPickUpOrder\x12\x1b.courier.PickUpOrderRequest\x1a\x1c.courier.PickUpOrderResponse\x12K\n" +
	"\fDeliverOrder\x12\x1c.courier.DeliverOrderRequest\x1a\x1d.courier.DeliverOrderResponseB=Z;github.com/suhrobdomoiZ/Eda-1/services/courier/internal/apib\x06proto3"

var (
	file_courier_proto_rawDescOnce sync.Once
	file_courier_proto_rawDescData []byte
)

func file_courier_proto_rawDescGZIP() []byte {
	file_courier_proto_rawDescOnce.Do(func() {
		file_courier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_courier_proto_rawDesc), len(file_courier_proto_rawDesc)))
	})
	return file_courier_proto_rawDescData
}

var file_courier_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_courier_proto_goTypes = []any{
	(*GetAvailableOrdersRequest)(nil),  // 0: courier.GetAvailableOrdersRequest
	(*GetAvailableOrdersResponse)(nil), // 1: courier.GetAvailableOrdersResponse
	(*AcceptOrderRequest)(nil),         // 2: courier.AcceptOrderRequest
	(*AcceptOrderResponse)(nil),        // 3: courier.AcceptOrderResponse
	(*GetMyOrdersRequest)(nil),         // 4: courier.GetMyOrdersRequest
	(*GetMyOrdersResponse)(nil),        // 5: courier.GetMyOrdersResponse
	(*PickUpOrderRequest)(nil),         // 6: courier.PickUpOrderRequest
	(*PickUpOrderResponse)(nil),        // 7: courier.PickUpOrderResponse
	(*DeliverOrderRequest)(nil),        // 8: courier.DeliverOrderRequest
	(*DeliverOrderResponse)(nil),       // 9: courier.DeliverOrderResponse
	(*common.Order)(nil),               // 10: common.Order
	(common.OrderStatus)(0),            // 11: common.OrderStatus
}
var file_courier_proto_depIdxs = []int32{
	10, // 0: courier.GetAvailableOrdersResponse.orders:type_name -> common.Order
	10, // 1: courier.AcceptOrderResponse.order:type_name -> common.Order
	10, // 2: courier.GetMyOrdersResponse.orders:type_name -> common.Order
	11, // 3: courier.PickUpOrderResponse.status:type_name -> common.OrderStatus
	11, // 4: courier.DeliverOrderResponse.status:type_name -> common.OrderStatus
	0,  // 5: courier.ClientAPI.GetAvailableOrders:input_type -> courier.GetAvailableOrdersRequest
	2,  // 6: courier.ClientAPI.AcceptOrder:input_type -> courier.AcceptOrderRequest
	4,  // 7: courier.ClientAPI.GetMyOrders:input_type -> courier.GetMyOrdersRequest
	6,  // 8: courier.ClientAPI.PickUpOrder:input_type -> courier.PickUpOrderRequest
	8,  // 9: courier.ClientAPI.DeliverOrder:input_type -> courier.DeliverOrderRequest
	1,  // 10: courier.ClientAPI.GetAvailableOrders:output_type -> courier.GetAvailableOrdersResponse
	3,  // 11: courier.ClientAPI.AcceptOrder:output_type -> courier.AcceptOrderResponse
	5,  // 12: courier.ClientAPI.GetMyOrders:output_type -> courier.GetMyOrdersResponse
	7,  // 13: courier.ClientAPI.PickUpOrder:output_type -> courier.PickUpOrderResponse
	9,  // 14: courier.ClientAPI.DeliverOrder:output_type -> courier.DeliverOrderResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_courier_proto_init() }
func file_courier_proto_init() {
	if File_courier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_courier_proto_rawDesc), len(file_courier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_courier_proto_goTypes,
		DependencyIndexes: file_courier_proto_depIdxs,
		MessageInfos:      file_courier_proto_msgTypes,
	}.Build()
	File_courier_proto = out.File
	file_courier_proto_goTypes = nil
	file_courier_proto_depIdxs = nil
}
