// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: customer.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CustomerAPI_CreateOrder_FullMethodName       = "/customer.CustomerAPI/CreateOrder"
	CustomerAPI_GetOrder_FullMethodName          = "/customer.CustomerAPI/GetOrder"
	CustomerAPI_CancelOrder_FullMethodName       = "/customer.CustomerAPI/CancelOrder"
	CustomerAPI_ListMyOrders_FullMethodName      = "/customer.CustomerAPI/ListMyOrders"
	CustomerAPI_GetRestaurantMenu_FullMethodName = "/customer.CustomerAPI/GetRestaurantMenu"
	CustomerAPI_ListRestaurants_FullMethodName   = "/customer.CustomerAPI/ListRestaurants"
)

// CustomerAPIClient is the client API for CustomerAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// API заказчика
type CustomerAPIClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
	ListMyOrders(ctx context.Context, in *ListMyOrdersRequest, opts ...grpc.CallOption) (*ListMyOrdersResponse, error)
	GetRestaurantMenu(ctx context.Context, in *GetRestaurantMenuRequest, opts ...grpc.CallOption) (*GetRestaurantMenuResponse, error)
	ListRestaurants(ctx context.Context, in *ListRestaurantsRequest, opts ...grpc.CallOption) (*ListRestaurantsResponse, error)
}

type customerAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerAPIClient(cc grpc.ClientConnInterface) CustomerAPIClient {
	return &customerAPIClient{cc}
}

func (c *customerAPIClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, CustomerAPI_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerAPIClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderResponse)
	err := c.cc.Invoke(ctx, CustomerAPI_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerAPIClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelOrderResponse)
	err := c.cc.Invoke(ctx, CustomerAPI_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerAPIClient) ListMyOrders(ctx context.Context, in *ListMyOrdersRequest, opts ...grpc.CallOption) (*ListMyOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyOrdersResponse)
	err := c.cc.Invoke(ctx, CustomerAPI_ListMyOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerAPIClient) GetRestaurantMenu(ctx context.Context, in *GetRestaurantMenuRequest, opts ...grpc.CallOption) (*GetRestaurantMenuResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRestaurantMenuResponse)
	err := c.cc.Invoke(ctx, CustomerAPI_GetRestaurantMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerAPIClient) ListRestaurants(ctx context.Context, in *ListRestaurantsRequest, opts ...grpc.CallOption) (*ListRestaurantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRestaurantsResponse)
	err := c.cc.Invoke(ctx, CustomerAPI_ListRestaurants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerAPIServer is the server API for CustomerAPI service.
// All implementations must embed UnimplementedCustomerAPIServer
// for forward compatibility.
//
// API заказчика
type CustomerAPIServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	ListMyOrders(context.Context, *ListMyOrdersRequest) (*ListMyOrdersResponse, error)
	GetRestaurantMenu(context.Context, *GetRestaurantMenuRequest) (*GetRestaurantMenuResponse, error)
	ListRestaurants(context.Context, *ListRestaurantsRequest) (*ListRestaurantsResponse, error)
	mustEmbedUnimplementedCustomerAPIServer()
}

// UnimplementedCustomerAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCustomerAPIServer struct{}

func (UnimplementedCustomerAPIServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedCustomerAPIServer) GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedCustomerAPIServer) CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedCustomerAPIServer) ListMyOrders(context.Context, *ListMyOrdersRequest) (*ListMyOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyOrders not implemented")
}
func (UnimplementedCustomerAPIServer) GetRestaurantMenu(context.Context, *GetRestaurantMenuRequest) (*GetRestaurantMenuResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRestaurantMenu not implemented")
}
func (UnimplementedCustomerAPIServer) ListRestaurants(context.Context, *ListRestaurantsRequest) (*ListRestaurantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRestaurants not implemented")
}
func (UnimplementedCustomerAPIServer) mustEmbedUnimplementedCustomerAPIServer() {}
func (UnimplementedCustomerAPIServer) testEmbeddedByValue()                     {}

// UnsafeCustomerAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomerAPIServer will
// result in compilation errors.
type UnsafeCustomerAPIServer interface {
	mustEmbedUnimplementedCustomerAPIServer()
}

func RegisterCustomerAPIServer(s grpc.ServiceRegistrar, srv CustomerAPIServer) {
	// If the following call panics, it indicates UnimplementedCustomerAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CustomerAPI_ServiceDesc, srv)
}

func _CustomerAPI_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerAPIServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerAPI_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerAPIServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerAPI_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerAPIServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerAPI_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerAPIServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerAPI_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerAPIServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerAPI_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerAPIServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerAPI_ListMyOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerAPIServer).ListMyOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerAPI_ListMyOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerAPIServer).ListMyOrders(ctx, req.(*ListMyOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerAPI_GetRestaurantMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestaurantMenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerAPIServer).GetRestaurantMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerAPI_GetRestaurantMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerAPIServer).GetRestaurantMenu(ctx, req.(*GetRestaurantMenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerAPI_ListRestaurants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRestaurantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerAPIServer).ListRestaurants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerAPI_ListRestaurants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerAPIServer).ListRestaurants(ctx, req.(*ListRestaurantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomerAPI_ServiceDesc is the grpc.ServiceDesc for CustomerAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomerAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "customer.CustomerAPI",
	HandlerType: (*CustomerAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _CustomerAPI_CreateOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _CustomerAPI_GetOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _CustomerAPI_CancelOrder_Handler,
		},
		{
			MethodName: "ListMyOrders",
			Handler:    _CustomerAPI_ListMyOrders_Handler,
		},
		{
			MethodName: "GetRestaurantMenu",
			Handler:    _CustomerAPI_GetRestaurantMenu_Handler,
		},
		{
			MethodName: "ListRestaurants",
			Handler:    _CustomerAPI_ListRestaurants_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer.proto",
}
